// Code generated by protoc-gen-go.
// source: userinfo.proto
// DO NOT EDIT!

/*
Package userinfo is a generated protocol buffer package.

It is generated from these files:
	userinfo.proto

It has these top-level messages:
	Ride
	RidesHistory
	UserAddr
	StartAddr
	DestAddr
	DidiStartAddr
	DidiDestAddr
*/
package userinfo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 乘客行程信息
type Ride struct {
	Routeid          *int64 `protobuf:"varint,1,req,name=routeid" json:"routeid,omitempty"`
	Lineid           *int64 `protobuf:"varint,2,opt,name=lineid" json:"lineid,omitempty"`
	Onstopid         *int64 `protobuf:"varint,3,opt,name=onstopid" json:"onstopid,omitempty"`
	Offstopid        *int64 `protobuf:"varint,4,opt,name=offstopid" json:"offstopid,omitempty"`
	Time             *int32 `protobuf:"varint,5,opt,name=time" json:"time,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Ride) Reset()         { *m = Ride{} }
func (m *Ride) String() string { return proto.CompactTextString(m) }
func (*Ride) ProtoMessage()    {}

func (m *Ride) GetRouteid() int64 {
	if m != nil && m.Routeid != nil {
		return *m.Routeid
	}
	return 0
}

func (m *Ride) GetLineid() int64 {
	if m != nil && m.Lineid != nil {
		return *m.Lineid
	}
	return 0
}

func (m *Ride) GetOnstopid() int64 {
	if m != nil && m.Onstopid != nil {
		return *m.Onstopid
	}
	return 0
}

func (m *Ride) GetOffstopid() int64 {
	if m != nil && m.Offstopid != nil {
		return *m.Offstopid
	}
	return 0
}

func (m *Ride) GetTime() int32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

// 乘客行程历史
type RidesHistory struct {
	Userid           *int64  `protobuf:"varint,1,req,name=userid" json:"userid,omitempty"`
	Arides           []*Ride `protobuf:"bytes,2,rep,name=arides" json:"arides,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RidesHistory) Reset()         { *m = RidesHistory{} }
func (m *RidesHistory) String() string { return proto.CompactTextString(m) }
func (*RidesHistory) ProtoMessage()    {}

func (m *RidesHistory) GetUserid() int64 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *RidesHistory) GetArides() []*Ride {
	if m != nil {
		return m.Arides
	}
	return nil
}

// 乘客家和公司地址坐标
type UserAddr struct {
	Userid           *int64   `protobuf:"varint,1,req,name=userid" json:"userid,omitempty"`
	Homelng          *float64 `protobuf:"fixed64,2,opt,name=homelng" json:"homelng,omitempty"`
	Homelat          *float64 `protobuf:"fixed64,3,opt,name=homelat" json:"homelat,omitempty"`
	Corplng          *float64 `protobuf:"fixed64,4,opt,name=corplng" json:"corplng,omitempty"`
	Corplat          *float64 `protobuf:"fixed64,5,opt,name=corplat" json:"corplat,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *UserAddr) Reset()         { *m = UserAddr{} }
func (m *UserAddr) String() string { return proto.CompactTextString(m) }
func (*UserAddr) ProtoMessage()    {}

func (m *UserAddr) GetUserid() int64 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *UserAddr) GetHomelng() float64 {
	if m != nil && m.Homelng != nil {
		return *m.Homelng
	}
	return 0
}

func (m *UserAddr) GetHomelat() float64 {
	if m != nil && m.Homelat != nil {
		return *m.Homelat
	}
	return 0
}

func (m *UserAddr) GetCorplng() float64 {
	if m != nil && m.Corplng != nil {
		return *m.Corplng
	}
	return 0
}

func (m *UserAddr) GetCorplat() float64 {
	if m != nil && m.Corplat != nil {
		return *m.Corplat
	}
	return 0
}

type StartAddr struct {
	Fromlng          *float64 `protobuf:"fixed64,1,opt,name=fromlng" json:"fromlng,omitempty"`
	Fromlat          *float64 `protobuf:"fixed64,2,opt,name=fromlat" json:"fromlat,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *StartAddr) Reset()         { *m = StartAddr{} }
func (m *StartAddr) String() string { return proto.CompactTextString(m) }
func (*StartAddr) ProtoMessage()    {}

func (m *StartAddr) GetFromlng() float64 {
	if m != nil && m.Fromlng != nil {
		return *m.Fromlng
	}
	return 0
}

func (m *StartAddr) GetFromlat() float64 {
	if m != nil && m.Fromlat != nil {
		return *m.Fromlat
	}
	return 0
}

type DestAddr struct {
	Tolng            *float64 `protobuf:"fixed64,3,opt,name=tolng" json:"tolng,omitempty"`
	Tolat            *float64 `protobuf:"fixed64,4,opt,name=tolat" json:"tolat,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *DestAddr) Reset()         { *m = DestAddr{} }
func (m *DestAddr) String() string { return proto.CompactTextString(m) }
func (*DestAddr) ProtoMessage()    {}

func (m *DestAddr) GetTolng() float64 {
	if m != nil && m.Tolng != nil {
		return *m.Tolng
	}
	return 0
}

func (m *DestAddr) GetTolat() float64 {
	if m != nil && m.Tolat != nil {
		return *m.Tolat
	}
	return 0
}

type DidiStartAddr struct {
	Userid           *int64       `protobuf:"varint,1,req,name=userid" json:"userid,omitempty"`
	Astartaddr       []*StartAddr `protobuf:"bytes,2,rep,name=astartaddr" json:"astartaddr,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *DidiStartAddr) Reset()         { *m = DidiStartAddr{} }
func (m *DidiStartAddr) String() string { return proto.CompactTextString(m) }
func (*DidiStartAddr) ProtoMessage()    {}

func (m *DidiStartAddr) GetUserid() int64 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *DidiStartAddr) GetAstartaddr() []*StartAddr {
	if m != nil {
		return m.Astartaddr
	}
	return nil
}

type DidiDestAddr struct {
	Userid           *int64      `protobuf:"varint,1,req,name=userid" json:"userid,omitempty"`
	Adestaddr        []*DestAddr `protobuf:"bytes,2,rep,name=adestaddr" json:"adestaddr,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *DidiDestAddr) Reset()         { *m = DidiDestAddr{} }
func (m *DidiDestAddr) String() string { return proto.CompactTextString(m) }
func (*DidiDestAddr) ProtoMessage()    {}

func (m *DidiDestAddr) GetUserid() int64 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

func (m *DidiDestAddr) GetAdestaddr() []*DestAddr {
	if m != nil {
		return m.Adestaddr
	}
	return nil
}
